### ISSUE TITLE
Textures will not load

### ISSUE THREAD

**Issue by RoloDoesMC** [InventivetalentDev/OneWayBlocks#1]
## What steps will reproduce the problem?  
1. Left click the first block
2. Right click the second block
3. Texture should load, but wont.

## What were you expecting to happen? What happened instead?  
Basically, after I click the the second block, the texture of the first block won't load on any side of the second block including the bottom.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
I am currently using version 1.3.0

## What Spigot version are you using? *Type /version* 
I am currently running spigot version 1.9

## What plugins ae you using? *Type /plugins*  
TNTRun, WorldEdit, ColoredSigns, ChatControl, NametagEdit, ProtocalLib, WorldBuard, PIxelator, Multiverse, LibsDisguises, NightVision, SignEdit, iDisguise, iConomy, Cault, ChairStairs, ColoredAnvils, Lores, Essentials, BlockHunt, Citizens, Essentials

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
I don't have any errors in my console

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
My client did not crash

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
From what I've heard, it seems like I am the only one with this problem. I am starting to suspect that it may be one of my plugins, but I'm not sure. If you have the time, you may visit the server and experiment with the plugin there to show you what is going on. The server ip is: play.mchaunt.com.

**Comment by InventivetalentDev** [comment]
What material are the blocks (The one you left-clicked and the one you right-clicked)?  
Does it work if you specify the material in the command (for example /oneWayWand stone)?

**Comment by RoloDoesMC** [comment]
For example, I want one side of a coal block to have glass to use as a one way window. The glass block is the one I left clifk, then I right click the coal block. This method doesn't work, and neither does the command. As I said before, it may be one of my plugins but as of yet I don't know

**Comment by InventivetalentDev** [comment]
Alright, the only plugin I could guess is WorldGuard, which could block entity spawning or you from interacting with the blocks. Other than that, I'm not sure. You can only try it on a separate server and test your plugins individually.

**Comment by RoloDoesMC** [comment]
That's what I've done, and it does work on that one.
I will start seeing which plugin is interfering with this. Thanks :D

**Comment by RoloDoesMC** [comment]
AHA! I figured it out. If you have world guard, and the region doesn't allow mob spawning, then the armor stand wont spawn in, thus not allowing it to work. If anyone else has to problem, make sure to tell them xD. Thanks again for the help!
